--- # section
lfc:
  ros__parameters:
    type: linear_feedback_controller/LinearFeedbackController
    urdf: /home/pdebbad/ros2_dev_ws/talos_harmonic/src/talos_harmonic/urdf/talos_without_grippers.urdf
    moving_joint_names: [
      arm_right_1_joint,
      arm_right_2_joint,
      arm_right_3_joint,
      arm_right_4_joint,
      arm_right_5_joint,
      arm_right_6_joint,
      arm_right_7_joint,
      arm_left_1_joint,
      arm_left_2_joint,
      arm_left_3_joint,
      arm_left_4_joint,
      arm_left_5_joint,
      arm_left_6_joint,
      arm_left_7_joint,
      leg_right_1_joint,
      leg_right_2_joint,
      leg_right_3_joint,
      leg_right_4_joint,
      leg_right_5_joint,
      leg_right_6_joint,
      leg_left_1_joint,
      leg_left_2_joint,
      leg_left_3_joint,
      leg_left_4_joint,
      leg_left_5_joint,
      leg_left_6_joint,
      torso_1_joint,
      torso_2_joint,
      head_1_joint,
      head_2_joint,
      # gripper_left_joint,
      # gripper_right_joint,
    ]
    arm_right_1_joint:
      p: 10000.0
      d: 0.01
    arm_right_2_joint:
      p: 10000.0
      d: 0.01
    arm_right_3_joint:
      p: 5000.0
      d: 0.01
    arm_right_4_joint:
      p: 5000.0
      d: 0.01
    arm_right_5_joint:
      p: 500.0
      d: 1.0
    arm_right_6_joint:
      p: 500.0
      d: 1.0
    arm_right_7_joint:
      p: 100.0
      d: 1.0
    arm_left_1_joint:
      p: 10000.0
      d: 0.01
    arm_left_2_joint:
      p: 10000.0
      d: 0.01
    arm_left_3_joint:
      p: 5000.0
      d: 0.01
    arm_left_4_joint:
      p: 5000.0
      d: 0.01
    arm_left_5_joint:
      p: 500.0
      d: 1.0
    arm_left_6_joint:
      p: 500.0
      d: 1.0
    arm_left_7_joint:
      p: 100.0
      d: 1.0
    leg_right_1_joint:
      p: 5000.0
      d: 20.0
    leg_right_2_joint:
      p: 5000.0
      d: 20.0
    leg_right_3_joint:
      p: 5000.0
      d: 20.0
    leg_right_4_joint:
      p: 5000.0
      d: 20.0
    leg_right_5_joint:
      p: 5000.0
      d: 20.0
    leg_right_6_joint:
      p: 5000.0
      d: 20.0
    leg_left_1_joint:
      p: 5000.0
      d: 20.0
    leg_left_2_joint:
      p: 5000.0
      d: 20.0
    leg_left_3_joint:
      p: 5000.0
      d: 20.0
    leg_left_4_joint: 
      p: 5000.0
      d: 20.0
    leg_left_5_joint:
      p: 5000.0
      d: 20.0
    leg_left_6_joint:
      p: 5000.0
      d: 20.0
    torso_1_joint:
      p: 10000.0
      d: 10.0
    torso_2_joint:
      p: 10000.0
      d: 10.0
    head_1_joint:
      p: 300.0
      d: 0.1
    head_2_joint:
      p: 300.0
      d: 0.1
    # gripper_left_joint:
    #   p: 0.0
    #   d: 0.0
    # gripper_right_joint:
    #   p: 0.0
    #   d: 0.0
    chainable_controller:
      reference_prefix: ''
      command_interfaces:
        - arm_right_1_joint_inertia_shaping_controller/arm_right_1_joint/effort
        - arm_right_2_joint_inertia_shaping_controller/arm_right_2_joint/effort
        - arm_right_3_joint_inertia_shaping_controller/arm_right_3_joint/effort
        - arm_right_4_joint_inertia_shaping_controller/arm_right_4_joint/effort
        - arm_right_5_joint_inertia_shaping_controller/arm_right_5_joint/effort
        - arm_right_6_joint_inertia_shaping_controller/arm_right_6_joint/effort
        - arm_right_7_joint_inertia_shaping_controller/arm_right_7_joint/effort
        - arm_left_1_joint_inertia_shaping_controller/arm_left_1_joint/effort
        - arm_left_2_joint_inertia_shaping_controller/arm_left_2_joint/effort
        - arm_left_3_joint_inertia_shaping_controller/arm_left_3_joint/effort
        - arm_left_4_joint_inertia_shaping_controller/arm_left_4_joint/effort
        - arm_left_5_joint_inertia_shaping_controller/arm_left_5_joint/effort
        - arm_left_6_joint_inertia_shaping_controller/arm_left_6_joint/effort
        - arm_left_7_joint_inertia_shaping_controller/arm_left_7_joint/effort
        - leg_right_1_joint_inertia_shaping_controller/leg_right_1_joint/effort
        - leg_right_2_joint_inertia_shaping_controller/leg_right_2_joint/effort
        - leg_right_3_joint_inertia_shaping_controller/leg_right_3_joint/effort
        - leg_right_4_joint_inertia_shaping_controller/leg_right_4_joint/effort
        - leg_right_5_joint_inertia_shaping_controller/leg_right_5_joint/effort
        - leg_right_6_joint_inertia_shaping_controller/leg_right_6_joint/effort
        - leg_left_1_joint_inertia_shaping_controller/leg_left_1_joint/effort
        - leg_left_2_joint_inertia_shaping_controller/leg_left_2_joint/effort
        - leg_left_3_joint_inertia_shaping_controller/leg_left_3_joint/effort
        - leg_left_4_joint_inertia_shaping_controller/leg_left_4_joint/effort
        - leg_left_5_joint_inertia_shaping_controller/leg_left_5_joint/effort
        - leg_left_6_joint_inertia_shaping_controller/leg_left_6_joint/effort
        - torso_1_joint_inertia_shaping_controller/torso_1_joint/effort
        - torso_2_joint_inertia_shaping_controller/torso_2_joint/effort
        - head_1_joint_inertia_shaping_controller/head_1_joint/effort
        - head_2_joint_inertia_shaping_controller/head_2_joint/effort
        # - gripper_left_joint_inertia_shaping_controller/gripper_left_joint/position
        # - gripper_right_joint_inertia_shaping_controller/gripper_right_joint/position
    remove_gravity_compensation_effort: false
    joint_velocity_filter_coefficient: 0.9
    pd_to_lf_transition_duration: 0.1
    robot_has_free_flyer: true
