use_sim: 
  default_value: 'True'
  
enable_crane:
  default_value: 'False'

test:
  default_value: 'False'

foot_collision:
  default_value: 'default'

disable_gazebo_camera:
  default_value: 'False'

use_grippers:
  default_value: 'False'