---
pd_plus_controller:
  ros__parameters:
    moving_joint_names: [
      arm_right_1_joint,
      arm_right_2_joint,
      arm_right_3_joint,
      arm_right_4_joint,
      arm_right_5_joint,
      arm_right_6_joint,
      arm_right_7_joint,
      arm_left_1_joint,
      arm_left_2_joint,
      arm_left_3_joint,
      arm_left_4_joint,
      arm_left_5_joint,
      arm_left_6_joint,
      arm_left_7_joint,
      leg_right_1_joint,
      leg_right_2_joint,
      leg_right_3_joint,
      leg_right_4_joint,
      leg_right_5_joint,
      leg_right_6_joint,
      leg_left_1_joint,
      leg_left_2_joint,
      leg_left_3_joint,
      leg_left_4_joint,
      leg_left_5_joint,
      leg_left_6_joint,
      torso_1_joint,
      torso_2_joint,
      head_1_joint,
      head_2_joint,
      gripper_left_joint,
      gripper_right_joint,
    ]
    amplitudes: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
    periods: [4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0]
    p_gains: [50.0, 50.0, 50.0, 50.0, 10.0, 5.0, 5.0, 50.0, 50.0, 50.0, 50.0, 10.0, 5.0, 5.0, 50.0, 50.0, 50.0, 50.0, 10.0, 5.0, 5.0, 50.0, 50.0, 50.0, 50.0, 10.0, 5.0, 5.0]
    d_gains: [0.5, 0.5, 0.5, 0.5, 0.3, 0.3, 0.0, 0.5, 0.5, 0.5, 0.5, 0.3, 0.3, 0.0, 0.5, 0.5, 0.5, 0.5, 0.3, 0.3, 0.0, 0.5, 0.5, 0.5, 0.5, 0.3, 0.3, 0.0, 0.5, 0.5, 0.5, 0.5]
    controller_period: 0.01