---
controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    torque_controller:
      type: effort_controllers/JointGroupEffortController
      joints:
        - torso_1_joint

    my_robot_hardware:
      hardware_class_type: gz_ros2_control/GzSystem
      joints:
        - name: torso_1_joint
          command_interfaces:
            - effort
          state_interfaces:
            - position
            - velocity
            - effort
